### ISSUE TITLE
error raised when running “python Cont_generate_dataset.py setcover_densize --density 0.05 -j 12”

### ISSUE THREAD

**Issue by fedoracy** [idea-iitd/LiMIP#1]
when running “python Cont_generate_dataset.py setcover_densize --density 0.05 -j 12”, error raised as, 
“[/nfs/OPTI/jenkins/workspace/SCIPOptSuite_linux_release/scipoptsuite-6.0.1/scip/src/scip/paramset.c:2001] ERROR: parameter <branching/vanillafullstrong/integralcands> unknown
[/nfs/OPTI/jenkins/workspace/SCIPOptSuite_linux_release/scipoptsuite-6.0.1/scip/src/scip/set.c:3086] ERROR: Error <-12> in function call
[/nfs/OPTI/jenkins/workspace/SCIPOptSuite_linux_release/scipoptsuite-6.0.1/scip/src/scip/scip_param.c:529] ERROR: Error <-12> in function call
Process Process-1:
Traceback (most recent call last):
  File "/home/u308/anaconda3/envs/mip_cy/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/u308/anaconda3/envs/mip_cy/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/u308/workspace/LiMIP-main/Cont_generate_dataset.py", line 149, in make_samples
    m.setBoolParam('branching/vanillafullstrong/integralcands', True)
  File "src/pyscipopt/scip.pyx", line 3528, in pyscipopt.scip.Model.setBoolParam
  File "src/pyscipopt/scip.pyx", line 235, in pyscipopt.scip.PY_SCIP_CALL
KeyError: 'SCIP: the parameter with the given name was not found!'
[/nfs/OPTI/jenkins/workspace/SCIPOptSuite_linux_release/scipoptsuite-6.0.1/scip/src/scip/paramset.c:2001] ERROR: parameter <branching/vanillafullstrong/integralcands> unknown
[/nfs/OPTI/jenkins/workspace/SCIPOptSuite_linux_release/scipoptsuite-6.0.1/scip/src/scip/set.c:3086] ERROR: Error <-12> in function call
[/nfs/OPTI/jenkins/workspace/SCIPOptSuite_linux_release/scipoptsuite-6.0.1/scip/src/scip/scip_param.c:529] ERROR: Error <-12> in function call
Process Process-2:
Traceback (most recent call last):
  File "/home/u308/anaconda3/envs/mip_cy/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/u308/anaconda3/envs/mip_cy/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/u308/workspace/LiMIP-main/Cont_generate_dataset.py", line 149, in ma”

**Comment by sahilm1992** [comment]
Hi,

This possibly seems an issue with SCIP installation/paths .

As mentioned in README, we request you  to install SCIP and other dependencies, follow the instructions of https://github.com/ds4dm/learn2branch/blob/master/INSTALL.md

The bug is not directly associated with the current repo.

The instructions in the above link should help you in installation.
